server:
  port: 8081

spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  cors:
    allowed-origins:
      - http://localhost:8080
      - http://localhost:3000
      - https://epia.store
      - https://www.epia.store
  files:
    local-base-dir: /tmp/epia-files

aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME:epia}
    region: ${AWS_REGION:ap-southeast-2}
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}